import type { NextConfig } from "next"
import fs from "fs"
import path from "path"

function generateRegistry() {
  const modulesDir = path.join(process.cwd(), "src", "_modules")
  if (!fs.existsSync(modulesDir)) return

  const items = fs.readdirSync(modulesDir)
  const modules: string[] = []

  for (const item of items) {
    const itemPath = path.join(modulesDir, item)
    if (fs.statSync(itemPath).isDirectory() && item !== "registry.ts") {
      modules.push(item)
    }
  }

  const pagesEntries: string[] = []
  const apisEntries: string[] = []
  const settingsEntries: string[] = []
  const adminApisEntries: string[] = []
  const adminLoginHooksEntries: string[] = []
  const userLoginHooksEntries: string[] = []

  const capitalize = (s: string) => s.charAt(0).toUpperCase() + s.slice(1)

  for (const mod of modules) {
    // 1. Public Pages (e.g., pages/index.tsx)
    const pagePath = path.join(modulesDir, mod, "pages", "index.tsx")
    if (fs.existsSync(pagePath)) {
      const routeKey = mod === "home" ? "" : mod
      pagesEntries.push(`  '${routeKey}': () => import('./${mod}/pages/index')`)
    }

    // 2. Public APIs (e.g., api/route.ts)
    const apiPath = path.join(modulesDir, mod, "api", "route.ts")
    if (fs.existsSync(apiPath)) {
      apisEntries.push(`  '${mod}': () => import('./${mod}/api/route')`)
    }

    // 3. Admin settings (e.g., admin/pages/settings.tsx)
    const settingsPath = path.join(modulesDir, mod, "admin", "pages", "settings.tsx")
    if (fs.existsSync(settingsPath)) {
      settingsEntries.push(`  '${mod}': {
    label: '${capitalize(mod)} Config',
    importFn: () => import('./${mod}/admin/pages/settings')
  }`)
    }

    // 4. Admin APIs (e.g., admin/api/route.ts)
    const adminApiPath = path.join(modulesDir, mod, "admin", "api/route.ts")
    if (fs.existsSync(adminApiPath)) {
      adminApisEntries.push(`  '${mod}': () => import('./${mod}/admin/api/route')`)
    }

    // 5. Admin login hooks (e.g., admin/login-hook.tsx)
    const adminLoginHookPath = path.join(modulesDir, mod, "admin", "login-hook.tsx")
    if (fs.existsSync(adminLoginHookPath)) {
      adminLoginHooksEntries.push(`  '${mod}-admin-login': {
    slot: 'actions',
    label: '${capitalize(mod)} Admin Login Hook',
    importFn: () => import('./${mod}/admin/login-hook')
  }`)
    }

    // 6. User login hooks (e.g., login-hook.tsx)
    const userLoginHookPath = path.join(modulesDir, mod, "login-hook.tsx")
    if (fs.existsSync(userLoginHookPath)) {
      userLoginHooksEntries.push(`  '${mod}-user-login': {
    slot: 'actions',
    label: '${capitalize(mod)} User Login Hook',
    importFn: () => import('./${mod}/login-hook')
  }`)
    }
  }

  const content = `// This file is auto-generated by next.config.ts. Do not edit.
import React from 'react'
import { links } from '../_utils/x-registry'

export interface PageModule {
  default: React.ComponentType<any>
}

export interface ApiModule {
  GET?: (request: Request, context: { params: Promise<{ slug: string[] }> }) => Promise<Response> | Response
  POST?: (request: Request, context: { params: Promise<{ slug: string[] }> }) => Promise<Response> | Response
  PUT?: (request: Request, context: { params: Promise<{ slug: string[] }> }) => Promise<Response> | Response
  DELETE?: (request: Request, context: { params: Promise<{ slug: string[] }> }) => Promise<Response> | Response
  PATCH?: (request: Request, context: { params: Promise<{ slug: string[] }> }) => Promise<Response> | Response
  HEAD?: (request: Request, context: { params: Promise<{ slug: string[] }> }) => Promise<Response> | Response
  OPTIONS?: (request: Request, context: { params: Promise<{ slug: string[] }> }) => Promise<Response> | Response
}

export interface SettingsModuleConfig {
  label: string
  importFn: () => Promise<{ default: React.ComponentType<any> }>
}

export interface LoginHookConfig {
  slot: 'top' | 'fields' | 'actions' | 'bottom'
  label: string
  importFn: () => Promise<{ default: React.ComponentType<any> }>
}

export const pagesRegistry: Record<string, () => Promise<PageModule>> = {
${pagesEntries.join(",\n")}
}

export const apisRegistry: Record<string, () => Promise<ApiModule>> = {
${apisEntries.join(",\n")}
}

export const moduleSettingsRegistry: Record<string, SettingsModuleConfig> = {
${settingsEntries.join(",\n")}
}

export const moduleApisRegistry: Record<string, () => Promise<any>> = {
${adminApisEntries.join(",\n")}
}

export const adminLoginHooksRegistry: Record<string, LoginHookConfig> = {
${adminLoginHooksEntries.join(",\n")}
}

export const userLoginHooksRegistry: Record<string, LoginHookConfig> = {
${userLoginHooksEntries.join(",\n")}
}

export function getModulePage(route: string) {
  let targetRoute = route
  if (links) {
    if (typeof (links as any).resolveLink === 'function') {
      const resolved = (links as any).resolveLink(route)
      if (resolved) {
        if (typeof resolved === 'string') {
          targetRoute = resolved
        } else if (resolved && typeof resolved === 'object' && resolved.module) {
          targetRoute = resolved.module
        }
      }
    } else if ((links as any).routes && typeof (links as any).routes === 'object') {
      const resolved = (links as any).routes[route]
      if (typeof resolved === 'string') {
        targetRoute = resolved
      } else if (resolved && typeof resolved === 'object' && resolved.module) {
        targetRoute = resolved.module
      }
    }
  }
  return pagesRegistry[targetRoute] || null
}

export function getModuleApi(route: string) {
  const parts = route.split('/')
  const base = parts[0]
  return apisRegistry[base] || null
}

export function getAdminModuleSettingsList() {
  return Object.entries(moduleSettingsRegistry).map(([key, value]) => ({
    key,
    label: value.label
  }))
}

export function getAdminModuleSettings(moduleKey: string) {
  return moduleSettingsRegistry[moduleKey] || null
}

export function getAdminModuleApi(route: string) {
  const parts = route.split('/')
  const base = parts[0]
  return moduleApisRegistry[base] || null
}

export function getAdminLoginHooks() {
  return Object.entries(adminLoginHooksRegistry).map(([key, value]) => ({
    id: key,
    slot: value.slot,
    importFn: value.importFn
  }))
}

export function getUserLoginHooks() {
  return Object.entries(userLoginHooksRegistry).map(([key, value]) => ({
    id: key,
    slot: value.slot,
    importFn: value.importFn
  }))
}
`

  fs.writeFileSync(path.join(modulesDir, "registry.ts"), content, "utf8")
}

function generateXRegistry() {
  const xDir = path.join(process.cwd(), "src", "_x")
  const utilsDir = path.join(process.cwd(), "src", "_utils")

  if (!fs.existsSync(xDir)) {
    fs.mkdirSync(xDir, { recursive: true })
  }

  const hasLinks = fs.existsSync(path.join(xDir, "links.ts"))
  const hasWorkflow = fs.existsSync(path.join(xDir, "workflow.ts"))

  let content = `// This file is auto-generated by next.config.ts. Do not edit.
`
  if (hasLinks) {
    content += `import * as customLinks from '../_x/links'
export const links = customLinks
`
  } else {
    content += `export const links = null
`
  }

  if (hasWorkflow) {
    content += `import * as customWorkflow from '../_x/workflow'
export const workflow = customWorkflow
`
  } else {
    content += `export const workflow = null
`
  }

  fs.writeFileSync(path.join(utilsDir, "x-registry.ts"), content, "utf8")
}

generateRegistry()
generateXRegistry()

const nextConfig: NextConfig = {
  output: "standalone",
}

export default nextConfig
