// This file is auto-generated by next.config.ts. Do not edit.
import React from 'react'
import { links } from '../_utils/x-registry'

export interface PageModule {
  default: React.ComponentType<any>
}

export interface ApiModule {
  GET?: (request: Request, context: { params: Promise<{ slug: string[] }> }) => Promise<Response> | Response
  POST?: (request: Request, context: { params: Promise<{ slug: string[] }> }) => Promise<Response> | Response
  PUT?: (request: Request, context: { params: Promise<{ slug: string[] }> }) => Promise<Response> | Response
  DELETE?: (request: Request, context: { params: Promise<{ slug: string[] }> }) => Promise<Response> | Response
  PATCH?: (request: Request, context: { params: Promise<{ slug: string[] }> }) => Promise<Response> | Response
  HEAD?: (request: Request, context: { params: Promise<{ slug: string[] }> }) => Promise<Response> | Response
  OPTIONS?: (request: Request, context: { params: Promise<{ slug: string[] }> }) => Promise<Response> | Response
}

export interface SettingsModuleConfig {
  label: string
  importFn: () => Promise<{ default: React.ComponentType<any> }>
}

export interface LoginHookConfig {
  slot: 'top' | 'fields' | 'actions' | 'bottom'
  label: string
  importFn: () => Promise<{ default: React.ComponentType<any> }>
}

export const pagesRegistry: Record<string, () => Promise<PageModule>> = {
  'products': () => import('./products/pages/index'),
  'websites': () => import('./websites/pages/index')
}

export const apisRegistry: Record<string, () => Promise<ApiModule>> = {
  'products': () => import('./products/api/route'),
  'websites': () => import('./websites/api/route')
}

export const moduleSettingsRegistry: Record<string, SettingsModuleConfig> = {
  'products': {
    label: 'Products Config',
    importFn: () => import('./products/admin/pages/settings')
  },
  'websites': {
    label: 'Websites Config',
    importFn: () => import('./websites/admin/pages/settings')
  }
}

export const moduleApisRegistry: Record<string, () => Promise<any>> = {
  'products': () => import('./products/admin/api/route'),
  'websites': () => import('./websites/admin/api/route')
}

export const adminLoginHooksRegistry: Record<string, LoginHookConfig> = {
  'websites-admin-login': {
    slot: 'actions',
    label: 'Websites Admin Login Hook',
    importFn: () => import('./websites/admin/login-hook')
  }
}

export const userLoginHooksRegistry: Record<string, LoginHookConfig> = {
  'websites-user-login': {
    slot: 'actions',
    label: 'Websites User Login Hook',
    importFn: () => import('./websites/login-hook')
  }
}

export function getModulePage(route: string) {
  let targetRoute = route
  if (links) {
    if (typeof (links as any).resolveLink === 'function') {
      const resolved = (links as any).resolveLink(route)
      if (resolved) {
        if (typeof resolved === 'string') {
          targetRoute = resolved
        } else if (resolved && typeof resolved === 'object' && resolved.module) {
          targetRoute = resolved.module
        }
      }
    } else if ((links as any).routes && typeof (links as any).routes === 'object') {
      const resolved = (links as any).routes[route]
      if (typeof resolved === 'string') {
        targetRoute = resolved
      } else if (resolved && typeof resolved === 'object' && resolved.module) {
        targetRoute = resolved.module
      }
    }
  }
  return pagesRegistry[targetRoute] || null
}

export function getModuleApi(route: string) {
  const parts = route.split('/')
  const base = parts[0]
  return apisRegistry[base] || null
}

export function getAdminModuleSettingsList() {
  return Object.entries(moduleSettingsRegistry).map(([key, value]) => ({
    key,
    label: value.label
  }))
}

export function getAdminModuleSettings(moduleKey: string) {
  return moduleSettingsRegistry[moduleKey] || null
}

export function getAdminModuleApi(route: string) {
  const parts = route.split('/')
  const base = parts[0]
  return moduleApisRegistry[base] || null
}

export function getAdminLoginHooks() {
  return Object.entries(adminLoginHooksRegistry).map(([key, value]) => ({
    id: key,
    slot: value.slot,
    importFn: value.importFn
  }))
}

export function getUserLoginHooks() {
  return Object.entries(userLoginHooksRegistry).map(([key, value]) => ({
    id: key,
    slot: value.slot,
    importFn: value.importFn
  }))
}
