import type { Metadata } from "next"
import localFont from "next/font/local"
import { InlineScript } from '@/_components/inline-script'
import "./globals.css"

const monaco = localFont({
  src: "../../public/fonts/monaco/Monaco.woff",
  variable: "--font-monaco",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const themeScript = `
(function () {
  try {
    var preference = localStorage.getItem('theme') || 'system'
    var systemDark = window.matchMedia('(prefers-color-scheme: dark)').matches
    var resolved = preference === 'system' ? (systemDark ? 'dark' : 'light') : preference
    document.documentElement.dataset.theme = resolved
    document.documentElement.dataset.themePreference = preference
  } catch (error) {}
})()
`

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${monaco.variable} h-full antialiased`}
    >
      <head>
        <InlineScript html={themeScript} />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  )
}
