import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const themeScript = `
(function () {
  try {
    var preference = localStorage.getItem('theme') || 'system'
    var systemDark = window.matchMedia('(prefers-color-scheme: dark)').matches
    var resolved = preference === 'system' ? (systemDark ? 'dark' : 'light') : preference
    document.documentElement.dataset.theme = resolved
    document.documentElement.dataset.themePreference = preference
  } catch (error) {}
})()
`

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  )
}
